version: "3.5"

services:
  pypi-cache-server:
    image: nginx
    volumes:
      - ./nginx-conf:/etc/nginx/nginx-conf
      # - nginx-cache-data:/var/cache/nginx/pypi:caâ€ ched
    command: "nginx-debug -g 'daemon off;' -c /etc/nginx/nginx-conf/nginx.conf"
    entrypoint: ""
    networks:
      - ntwrk

  pypiserver:
    image: pypiserver/pypiserver
    command: "-P . -a ."
    healthcheck:
      test: ["CMD", "python", "-c", "\"import urllib.request;print(urllib.request.urlopen('http://pypiserver:8080/simple').readlines())\""]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - ntwrk

  publisher:
    build:
      dockerfile: pypi/Dockerfile
      context: ..
    depends_on:
      pypiserver:
        condition: service_healthy
    command: "twine upload --verbose -u foo -p bar --repository-url http://pypiserver:8080/ dist/*"
    networks:
      - ntwrk

networks:
  ntwrk:
    driver: bridge
    name: ntwrk

volumes:
  nginx-cache-data:
    driver: local